#!/usr/bin/env ruby

require 'date'

def exit_with_usage_instructions
  puts <<EOS
I'd cheer for you, if only I knew who you were :(
Try again with `./cheers.rb [Name] [MM/DD Birthday]
EOS
  exit
end
exit_with_usage_instructions if ARGV.empty?
original_name = ARGV[0]
cheerable_name = original_name.upcase.gsub(/[^A-Z]/, "")
exit_with_usage_instructions if cheerable_name.empty?
cheerable_name.each_char do |char|
  article = "n" if "HALFNORSEMIX".include? char
  puts "Give me a#{article}... #{char}"
end
puts "#{original_name}’s just GRAND!"

begin
  birthday = Date.parse(ARGV[1]).yday
  now      = Time.new.yday
  diff     = (birthday - now)

  if ARGV[1].length > 5
    puts "I would wish you a Happy Birthday, if I knew when that was!"
  else
    puts "Awesome! Your birthday is in #{diff+1} days! Happy Birthday in advance!"
  end
rescue
  puts "I would wish you a Happy Birthday, if I knew when that was!"
end
